from colorama import init, Fore
from collections import Counter

init(autoreset=True)

print()
print("counterModule.py")
print()
counter_numbers = Counter([5, 1, 5, 1, 5, 2])
print("counter_numbers = Counter([5, 1, 5, 1, 5, 2])")
print("Counter Method Used List Of Integers")
print("-----------------------------------")
print(f"Counter Numbers: {counter_numbers}")  # Output: Counter({5: 3, 1: 2, 2: 1})
print(f"Type of counter_numbers: {type(counter_numbers)}")  # Output: <class 'collections.Counter'>
print("-----------------------------------")
print()
print("Elements Method Used Counter Object")
print("------------------------------------")
elements_list = list(counter_numbers.elements())
print("elements = counter_numbers.elements()")
print("Elements:", elements_list)  # Output: [5, 5, 5, 1, 1, 2]
sorted_elements = sorted(elements_list)
print("sorted_elements = sorted(list(elements))")
print("Sorted Elements:", sorted_elements)  # Output: [1, 1, 2, 5, 5, 5]
print("-----------------------------------")
print()
print("Most Common Method Used Counter Object")
most_common = counter_numbers.most_common()
print("most_common = counter_numbers.most_common()")
print("Most Common:", most_common)  # Output: [(5, 3), (1, 2), (2, 1)]
most_common_2 = counter_numbers.most_common(2)
print("most_common_2 = counter_numbers.most_common(2)")
print("Most Common 2:", most_common_2)  # Output: [(5, 3), (1, 2)]
print("-----------------------------------")
print()
print("Subtract Method Used Counter Object")
print("-----------------------------------")
print(Fore.RED + "subtractメソッドは、元のCounterオブジェクトに対して減算をするため、注意が必要です。")
new_counter_numbers = Counter([5, 1, 2])
print("new_counter_numbers = Counter([5, 1, 2])")
substract_counter_numbers = Counter([5, 1, 2])
print("substract_counter_numbers = Counter([5, 1, 2])")
substract_counter_numbers.subtract(new_counter_numbers)
print("substract_counter_numbers.subtract(new_counter_numbers)")
print("New Counter Numbers After Subtract:", substract_counter_numbers)  # Output: Counter({5: 0, 1: 0, 2: 0})
print("-----------------------------------")
print()
print("Update Method Used Counter Object")
print("-----------------------------------")
print(Fore.RED + "updateメソッドは、元のCounterオブジェクトに対して加算をするため、注意が必要です。")
update_counter_numbers = Counter([5, 1, 2])
print("update_counter_numbers = Counter([5, 1, 2])")
update_counter_numbers.update(new_counter_numbers)
print("update_counter_numbers.update(new_counter_numbers)")
print("New Counter Numbers After Update:", update_counter_numbers)  # Output: Counter({5: 2, 1: 2, 2: 2})
print("-----------------------------------")
print()
print("Operand Method Used Counter Object")
print("-----------------------------------")
print(Fore.RED + "Counterオブジェクトは、加算、減算、積、和の演算子をサポートしていますが、これらの演算は新しいCounterオブジェクトを返すため、元のCounterオブジェクトは変更されません。")
counter1 = Counter([5, 1, 2])
print("counter1 = Counter([5, 1, 2])")
counter2 = Counter([5, 1])
print("counter2 = Counter([5, 1])")
print("Counterオブジェクトの加算")
counter_sum = counter1 + counter2
print("counter_sum = counter1 + counter2")
print("Counter Sum:", counter_sum)  # Output: Counter({5: 2, 1: 2, 2: 2})
print("Counterオブジェクトの減算")
counter_difference = counter1 - counter2
print("counter_difference = counter1 - counter2")
print("Counter Difference:", counter_difference)
print("Counterオブジェクトの減算（Counterオブジェクトなし）")
counter_difference_nocounter = counter1 - Counter([5, 1, 2])
print("counter_difference_nocounter = counter1 - Counter([5, 1, 2])")
print("Counter Difference No Counter:", counter_difference_nocounter)  # Output: Counter()
print("Counterオブジェクトの積")
counter_intersection = counter1 & counter2
print("counter_intersection = counter1 & counter2")
print("Counter Intersection:", counter_intersection)  # Output: Counter({5: 1, 1: 1, 2: 1})
print("Counterオブジェクトの和")
counter_union = counter1 | counter2
print("counter_union = counter1 | counter2")
print("Counter Union:", counter_union)  # Output: Counter({5: 1, 1: 1, 2: 1})
print("-----------------------------------")
print()
print("Minus Counter Object")
print("------------------------------------")
print(Fore.RED + "Counterオブジェクトは、負のカウントを持つことができますが、elements()メソッドは、正のカウントのみを返すため、負のカウントは無視されます。")
c = Counter(a=3, b=2, c=-1)
print("c = Counter(a=3, b=2, c=-1)")
print("c:", c)  # Output: Counter({'a': 3, 'b': 2, 'c': -1})
print("list(c.elements()):", list(c.elements()))  # Output: ['a', 'a', 'a', 'b', 'b']
print("------------------------------------")
print()
print("Culculate Counter Object")
print("------------------------------------")
print(Fore.RED + "Counterオブジェクトは、合計、平均、最大値、最小値などの統計情報を簡単に計算することができます。")
a = Counter(a=3, b=2, c=-1)
print("a = Counter(a=3, b=2, c=-1)")
b = Counter(a=1, b=1, c=1)
print("b = Counter(a=1, b=1, c=1)")
print("a + b:", a + b)  # Output: Counter({'a': 4, 'b': 3, 'c': 0})
print("a - b:", a - b)  # Output: Counter({'a': 2, 'b': 1})
try:
    print("a * b")
    print("a / b")
    print("a * b:", a * b)  # Output: Counter({'a': 3, 'b': 2, 'c': -1})
    print("a / b:", a / b)  # Output: Counter({'a': 3.0, 'b': 2.0, 'c': -1.0})
except TypeError as e:
    print(f"TypeError: {e}", "Counterオブジェクトは、乗算や除算の演算子をサポートしていません。")
print("a & b:", a & b)  # Output: Counter({'a': 1, 'b': 1})
print("a | b:", a | b)  # Output: Counter({'a': 3, 'b': 2, 'c': 1})
print("------------------------------------")
print()
print("Infuluence Counter Object")
print("------------------------------------")
print(Fore.RED + "Counterオブジェクトは、他のCounterオブジェクトや辞書、リストなどのイテラブルなオブジェクトから影響を受けることがあります。")
counter_a = Counter(a=3, b=2, c=-1)
print("counter_a = Counter(a=3, b=2, c=-1)")
couter_new = counter_a + Counter(a=1, b=1, c=1)
print("couter_new = counter_a + Counter(a=1, b=1, c=1)")
print("Counter New:", couter_new)  # Output: Counter({'a': 4, 'b': 3, 'c': 0})
print("Counter_a:", counter_a)  # Output: Counter({'a': 3, 'b': 2, 'c': -1})
print("------------------------------------")
print()